# Speed reading qualitative assessments of public company performance {#speed-reading}

####Keywords 
NLP, annual report, industry analysis, 10-K

## Problem: 
The qualitative data in annual reports is costly and time consuming to review. The performance of public companies is largely considered in terms of the quantitative data in annual reports. The qualitative context that makes up the bulk of the report contains can contain revealing information about a company's operations. [@goel_sentiments_2016] However, this information is largely ignored and poured over only by industry-specific analysts at investment firms. Analysts have spent thousands of hours working in the industry and spend countless additional hours parsing the text to update the view of the competitive landscape and make company specific recommendations.

If we take the telecommunications industry as an example, in a little over a year, assuming net neutrality is repealed, companies will be sharing their plans to address this change in the regulatory environment. It is likely to still be too early to see a difference in revenue, though there may be some changes in investment. The description of the opportunity that companies see in the space will be one of the best leading indicators for competitive changes in the industry. And NLP would allow for easy comparison of how much emphasis each firm is putting on the opportunity.

Interpreting and comparing reports is expensive and time consuming. GE's 2016 Annual Report, for example, is 264 pages.  Because of the cost to synthesize this information, it is too expensive and inaccessible for use cases beyond institutional investing. From a practical perspective, individual investers and business leaders in small to medium-sized firms have limited access to this information.  For example, if I am the head of strategy at Gogo, a mid-sized telecom company focused on in-flight, internet and entertainment, I would want to have an informed hypothsis on how competitors will respond to rule changes and what that will mean for the experience customers will have when using Gogo's product compared to other internet providers.  I would not have the resources to review all of the reports in any detail.   

## Solution: 
Natural language processing(NLP) of annual reports in a specific industry can create an insightful view of the competitive landscape and a specific company’s response.  The industry analysis would be made publically available.  The competitive comparison and company-specific reports would be available for a fee.  

The application of NLP could support the following research questions: 
-What are the primary headwinds/tailwinds (or factors) impacting the industry? 
-What is the sentiment surrounding key challenges and opportunities? 
-For each company in the industry, how do they prioritize each factor? 
-For key factors, how does each company’s level of investment compare to their amount of qualitative coverage in their report?

Development of the solution would include comparing supervised and unsupervised learning models.  Supervised learning models will rely on experts to align text to specific factors.  These factors will create a strong backbone for summarizing company comparisons.  Unsupervised learning models can help identify unforeseen factors, changes in the environment and unexpected topics to eventually be added to the supervised model.    

## Impact: 
Continuing our hypothetical example, the head of corporate strategy and CEO at Gogo are planning to facilitate a conversation with business leaders on the degree to which their product should change due to the repeal of net neutrality.  Because in-flight consumers naturally compare their experience with in home use, understanding competitive changes in the user experience is particularly important.  Using an NLP-powered competitive report, they share a stack rank of the extent to which competitors are likely to change their internet offerings.  This visual allows the conversation to focus on what is the right degree of change for their business to take on, rather than debating what folks believe may change.  This is a level of insight that was previously not available to this team.        

